<a href="https://colab.research.google.com/github/ashleytrivino/arms_transfer_dsrp/blob/main/Ashley_Trivino_Arms_Transfer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/arms_transfers_clean.csv')
df.head()
df_dupe = pd.read_csv('/content/arms_transfers_clean.csv')

In [33]:
df.info()
# number ordered, deliveries in the year range, year(s) of delivery have missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9756 entries, 0 to 9755
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Recipient                       9756 non-null   object
 1   Supplier                        9756 non-null   object
 2   Year of order                   9756 non-null   int64
 3   Number ordered                  9670 non-null   float64
 4   Weapon designation              9756 non-null   object
 5   Weapon description              9756 non-null   object
 6   Deliveries in the Year Range    9333 non-null   float64
 7   Year(s) of delivery             9333 non-null   object
 8   status                          9756 non-null   object
 9   SIPRI TIV per unit              9756 non-null   float64
 10  SIPRI TIV for total order       9756 non-null   float64
 11  SIPRI TIV of delivered weapons  9756 non-null   float64
dtypes: float64(5), int64(1), object(6)
memory usage: 914.8+ KB

In [34]:
df.describe()

,Year of order,Number ordered,Deliveries in the Year Range,SIPRI TIV per unit,SIPRI TIV for total order,SIPRI TIV of delivered weapons
count,9756.000000,9670.000000,9333.000000,9756.000000,9756.000000,9756.000000
mean,1987.274703,156.860703,154.585664,7.443830,94.357230,83.811894
std,22.060454,987.060460,997.650698,23.468209,337.544437,303.717951
min,1940.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,1969.000000,3.000000,3.000000,0.240000,5.000000,4.200000
50%,1986.000000,12.000000,12.000000,1.000000,18.000000,16.000000
75%,2008.000000,60.000000,57.000000,5.000000,56.000000,52.575000
max,2025.000000,50000.000000,50000.000000,700.000000,10117.500000,10117.500000

In [36]:
df.columns

Index(['Recipient', 'Supplier', 'Year of order', 'Number ordered',
       'Weapon designation', 'Weapon description',
       'Deliveries in the Year Range', 'Year(s) of delivery', 'status',
       'SIPRI TIV per unit', 'SIPRI TIV for total order',
       'SIPRI TIV of delivered weapons'],
      dtype='object')

In [41]:
df = df.rename(columns={"status":"Status", "Weapon description":"Weapon Description", "Year of order":"Year of Order",
                        "Weapon designation":"Weapon Designation", "Year(s) of delivery":"Year(s) of Delivery",
                        "SIPRI TIV per unit":"SIPRI TIV per Unit", "SIPRI TIV for total order":"SIPRI TIV for Total Order",
                        "SIPRI TIV of delivered weapons":"SIPRI TIV of Delivered Weapons",
                        "Number ordered":"Number Ordered"})

In [42]:
df.columns

Index(['Recipient', 'Supplier', 'Year of Order', 'Number Ordered',
       'Weapon Designation', 'Weapon Description',
       'Deliveries in the Year Range', 'Year(s) of Delivery', 'Status',
       'SIPRI TIV per Unit', 'SIPRI TIV for Total Order',
       'SIPRI TIV of Delivered Weapons'],
      dtype='object')

In [46]:
df = df.drop_duplicates()

In [47]:
df.info()
# number ordered, deliveries in the year range, year(s) of delivery have missing values
# number ordered and deliveries in the year range are floats
# year(s) of delivery is an object since there are multiple numbers

<class 'pandas.core.frame.DataFrame'>
Index: 9741 entries, 0 to 9755
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Recipient                       9741 non-null   object
 1   Supplier                        9741 non-null   object
 2   Year of Order                   9741 non-null   int64
 3   Number Ordered                  9656 non-null   float64
 4   Weapon Designation              9741 non-null   object
 5   Weapon Description              9741 non-null   object
 6   Deliveries in the Year Range    9319 non-null   float64
 7   Year(s) of Delivery             9319 non-null   object
 8   Status                          9741 non-null   object
 9   SIPRI TIV per Unit              9741 non-null   float64
 10  SIPRI TIV for Total Order       9741 non-null   float64
 11  SIPRI TIV of Delivered Weapons  9741 non-null   float64
dtypes: float64(5), int64(1), object(6)
memory usage: 989.3+ KB

In [49]:
df = df.dropna(axis = 0, how = 'any', subset = ['Number Ordered', 'Deliveries in the Year Range'])

This dropped any rows with null values in either the 'Number Ordered' column or 'Deliveries in the Year Range' column

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9282 entries, 0 to 9755
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Recipient                       9282 non-null   object
 1   Supplier                        9282 non-null   object
 2   Year of Order                   9282 non-null   int64
 3   Number Ordered                  9282 non-null   float64
 4   Weapon Designation              9282 non-null   object
 5   Weapon Description              9282 non-null   object
 6   Deliveries in the Year Range    9282 non-null   float64
 7   Year(s) of Delivery             9282 non-null   object
 8   Status                          9282 non-null   object
 9   SIPRI TIV per Unit              9282 non-null   float64
 10  SIPRI TIV for Total Order       9282 non-null   float64
 11  SIPRI TIV of Delivered Weapons  9282 non-null   float64
dtypes: float64(5), int64(1), object(6)
memory usage: 942.7+ KB

In [61]:
df.describe()

,Year of Order,Number Ordered,Deliveries in the Year Range,SIPRI TIV per Unit,SIPRI TIV for Total Order,SIPRI TIV of Delivered Weapons
count,9282.000000,9282.000000,9282.000000,9282.000000,9282.000000,9282.000000
mean,1985.493967,155.064426,151.068197,7.370628,92.084891,87.841741
std,21.084221,995.695751,978.172262,23.537195,333.621893,310.788416
min,1940.000000,1.000000,1.000000,0.000000,0.040000,0.040000
25%,1968.000000,3.000000,3.000000,0.240000,5.170000,5.040000
50%,1984.000000,12.000000,12.000000,1.000000,18.000000,18.000000
75%,2004.000000,59.000000,56.000000,5.000000,56.000000,55.000000
max,2025.000000,50000.000000,50000.000000,700.000000,10117.500000,10117.500000

In [62]:
df.head()

,Recipient,Supplier,Year of Order,Number Ordered,Weapon Designation,Weapon Description,Deliveries in the Year Range,Year(s) of Delivery,Status,SIPRI TIV per Unit,SIPRI TIV for Total Order,SIPRI TIV of Delivered Weapons
0,Afghanistan,United States,2015,55.0,M-1117 Guardian,armoured personnel carrier,55.0,2015,New,0.40,22.0,22.0
1,Afghanistan,United States,2004,188.0,M-113,armoured personnel carrier,188.0,2005,Second hand,0.10,18.8,18.8
2,Afghanistan,United States,2017,1673.0,HMMWV-UA,armoured personnel carrier,1673.0,2018; 2019; 2020; 2021,Second hand,0.05,87.0,87.0
3,Afghanistan,United States,2006,800.0,HMMWV-UA,armoured personnel carrier,800.0,2007; 2008,Second hand,0.05,41.6,41.6
4,Afghanistan,United States,2011,41.0,M-1117 Guardian,armoured personnel carrier,41.0,2011; 2012,New,0.40,16.4,16.4